# Generated by Django 4.2.2 on 2023-06-23 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='username',
        ),
    ]
